### ISSUE TITLE
Material design: entire scroll regions repaints

### ISSUE THREAD

**Issue by ebidel** [google/WebFundamentals#2022]
Turn on show paint rects. Scrolling the page, you can see the entire content (scroll container) repaints.

**Comment by paulirish** [comment]
This'll fix it: 

```css
.mdl-layout__content {
   will-change: transform;
}
```
