### ISSUE TITLE
Improve code snippet for responsive videos and embeds

### ISSUE THREAD

**Issue by srus** [google/WebFundamentals#4030]
The code snippet suggested in [this page](https://developers.google.com/web/fundamentals/design-and-ui/media/video#ensure_videos_dont_overflow_containers) to make videos and embeds responsive can be improved using a 16:9 aspect ratio by default in order to avoid blank lines in most of the videos. So the following CSS rule:

```CSS
.video-container {
    position: relative;
    padding-bottom: 56.25%;
    padding-top: 30px;
    height: 0;
    overflow: hidden;
}
```
should be using **`padding-top: 0;`**
