### ISSUE TITLE
Set the background color for the HTML body element

### ISSUE THREAD

**Issue by xchs** [google/WebFundamentals#469]
Add a background color CSS style property for the `<body>` element, e.g.

``` css
body {
    background-color: #ffffff;
    …
}
```
