### ISSUE TITLE
[Lighthouse / Blocking Resources / Helpful]

### ISSUE THREAD

**Issue by tedsecretsource** [google/WebFundamentals#6271]
**Page Affected:** https://developers.google.com/web/tools/lighthouse/audits/blocking-resources

**What needs to be done?**

Add examples of "inlining" for both scripts and styles. Something like:

***Original***
```html
<link href="https://google.com/content-body.css" rel="stylesheet" media="screen and (min-width: 400px)" />
```

***Becomes***
```css
<style>
@media screen and (min-width: 400px)
{
    body.content
    {
        margin: 0px 20px;
    }
}
</style>
```

And this could be made better with a clearer example of what is considered "critical" CSS.

Thanks!
