### ISSUE TITLE
_contributors.yaml description field does not allow for localization

### ISSUE THREAD

**Issue by jbnicolai** [google/WebFundamentals#728]
The `yaml` format is currently:

``` yaml
{{github name}}:
  name: 
    given: {{given name}}
    family: {{family name}}
  org:
    name: {{org name}}
    unit: {{org unit name}}
  country: {{country code}}
  role:
    - {{role list}}
  homepage: {{url}}
  google: {{google plus handle}}
  twitter: {{twitter handle}}
  email: {{email adress}}
  description: {{personal description}}
```

Currently all descriptions are in English, which does not allow for localisation.

I suggest the correct locale be injected in Jekyll during compilation (if this does not already happen), and the description property be changed from a string to an alphabetically ordered map `[{{locale}} -> {{localised description}}]`. The keys would use [`iso 369-2`](http://www.loc.gov/standards/iso639-2/php/code_list.php) to identify languages and the description would be in the corresponding language.

E.g.:

``` yaml
jbnicolai:
  description:
    de: "Joshua ist ein Pirat"
    en: "Joshua is a pirate"
    fr: "Joshua est un pirate"
    la: "Joshua est pirata"
    ru: "Dzhoshua yavlyayetsya piratom"
    nl: "Joshua is een piraat"
```
