### ISSUE TITLE
CSS styles missing in "Animating Between Views" article

### ISSUE THREAD

**Issue by nbeloglazov** [google/WebFundamentals#918]
In the article you toggle `view-change` class from javascript:

``` js
function onViewChange(evt) {
  container.classList.toggle('view-change');
}
```

But the styles for that class were never defined in the article, so it is essentially no-op. The styles are present in the [sample](http://googlesamples.github.io/web-fundamentals/samples/look-and-feel/animations/inter-view-animation.html) though:

``` css
.view-change .list-view {
  -webkit-transform: translateX(-100%);
  transform: translateX(-100%);
}

.view-change .details-view {
  -webkit-transform: translateX(0);
  transform: translateX(0);
}
```

I think the styles should be added to the article.
